#!/usr/bin/env python3
"""
train.py — NEXUS+ Forensic Training, Memory Bank & Spec-Matching Terminal
═════════════════════════════════════════════════════════════════════════
Interactive and CLI tool to train images (GENERATED BY AI, AI-EDITED, AUTHENTIC),
extract & remember full forensic specs, and analyze suspect images to match
trained exemplars and deliver identical learned verdicts.

Usage:
  Interactive Menu:
    python train.py

  CLI Arguments:
    python train.py --train <image_path> --label <generated_by_ai|ai_edited|real> [--notes <text>]
    python train.py --match <image_path>
    python train.py --list
    python train.py --batch <folder_path> --label <generated_by_ai|ai_edited|real>
"""

import os
import sys
import json
import argparse
import time
from pathlib import Path
from PIL import Image

# Ensure UTF-8 output encoding in Windows terminals
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

# Ensure project root is in sys.path
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

def _get_cached_registry():
    reg_file = ROOT / "results" / "authenticated_registry.json"
    if reg_file.exists():
        try:
            with open(reg_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            return {}
    return {}

# ─────────────────────────────────────────────────────────────
# ANSI CYBER STYLING FOR TERMINAL
# ─────────────────────────────────────────────────────────────

USE_COLOR = sys.stdout.isatty() or os.environ.get("TERM")

if sys.platform == "win32":
    try:
        import ctypes
        kernel32 = ctypes.windll.kernel32
        kernel32.SetConsoleMode(kernel32.GetStdHandle(-11), 7)
    except Exception:
        pass

C_RESET   = "\033[0m" if USE_COLOR else ""
C_BOLD    = "\033[1m" if USE_COLOR else ""
C_DIM     = "\033[2m" if USE_COLOR else ""
C_CYAN    = "\033[96m" if USE_COLOR else ""
C_MAGENTA = "\033[95m" if USE_COLOR else ""
C_BLUE    = "\033[94m" if USE_COLOR else ""
C_GREEN   = "\033[92m" if USE_COLOR else ""
C_YELLOW  = "\033[93m" if USE_COLOR else ""
C_RED     = "\033[91m" if USE_COLOR else ""
C_BG_DARK = "\033[40m" if USE_COLOR else ""


def print_banner():
    banner = f"""
{C_MAGENTA}{C_BOLD}╔═══════════════════════════════════════════════════════════════════════════╗
║   ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗  ██████╗ ██╗   ██╗███████╗  ║
║   ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝  ██╔══██╗██║   ██║██╔════╝  ║
║   ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗  ██████╔╝██║   ██║███████╗  ║
║   ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║  ██╔═══╝ ██║   ██║╚════██║  ║
║   ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║  ██║     ╚██████╔╝███████║  ║
║   ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝  ╚═╝      ╚═════╝ ╚══════╝  ║
║         -- FORENSIC MEMORY, SPEC-LEARNING & EXEMPLAR ENGINE --            ║
╚═══════════════════════════════════════════════════════════════════════════╝{C_RESET}
"""
    print(banner)


def clean_input_path(p: str) -> str:
    """Clean quotes, whitespace, and escape characters from terminal input."""
    p = p.strip()
    if (p.startswith('"') and p.endswith('"')) or (p.startswith("'") and p.endswith("'")):
        p = p[1:-1]
    return p.strip()


def display_specs_card(specs: dict, title: str = "EXTRACTED FORENSIC SPECS"):
    res = specs.get("resolution", {})
    col = specs.get("color_profile", {})
    freq = specs.get("frequency_specs", {})
    tex = specs.get("texture_specs", {})
    noise = specs.get("noise_specs", {})

    print(f"\n{C_CYAN}{C_BOLD}┌── [ {title} ] ──────────────────────────────────────────{C_RESET}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}SHA-256:{C_RESET}          {C_YELLOW}{specs.get('sha256')}{C_RESET}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}Perceptual dHash:{C_RESET} {C_MAGENTA}{specs.get('dhash')}{C_RESET}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}Resolution:{C_RESET}       {res.get('width')}x{res.get('height')} px ({res.get('aspect_ratio')}:1) · {res.get('megapixels', 0)} MP")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}Color Saturation:{C_RESET} Mean: {col.get('saturation_mean')} | Std: {col.get('saturation_std')} | Skew: {col.get('saturation_skew')}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}2D FFT Spectrum:{C_RESET}  High-Freq Ratio: {freq.get('high_frequency_ratio')} | Energy Decay: {freq.get('spectral_energy_decay')}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}Texture Metrics:{C_RESET}  Laplacian Var: {tex.get('laplacian_variance')} | Micro-Smoothness: {tex.get('micro_smoothness')}")
    print(f"{C_CYAN}│{C_RESET}  {C_BOLD}Sensor Noise:{C_RESET}     Residual STD: {noise.get('sensor_noise_std')} | Patch Disparity: {noise.get('patch_noise_disparity')}")
    print(f"{C_CYAN}└────────────────────────────────────────────────────────────────────────{C_RESET}\n")


def train_single_interactive():
    print(f"\n{C_BOLD}{C_MAGENTA}=== [1] TRAIN & REMEMBER IMAGE ==={C_RESET}")
    path_raw = input(f"{C_CYAN}Enter image file path (or drag & drop): {C_RESET}")
    img_path = clean_input_path(path_raw)

    if not os.path.exists(img_path):
        print(f"{C_RED}[ERROR] File not found: {img_path}{C_RESET}")
        return

    try:
        Image.open(img_path).verify()
    except Exception as e:
        print(f"{C_RED}[ERROR] Invalid image file: {e}{C_RESET}")
        return

    print(f"\n{C_BOLD}Select Training Category / Ground Truth Label:{C_RESET}")
    print(f"  {C_RED}[1] GENERATED BY AI{C_RESET}     (Fully synthetic Midjourney, Flux, SDXL, DALL-E render)")
    print(f"  {C_YELLOW}[2] AI-EDITED{C_RESET}            (Authentic camera base with AI inpainting/generative fill)")
    print(f"  {C_GREEN}[3] AUTHENTIC / REAL{C_RESET}     (Original genuine optical camera capture)")
    
    choice = input(f"{C_CYAN}Select option [1-3] (Default 1): {C_RESET}").strip()
    if choice == "2":
        label = "ai_edited"
        label_str = "AI-EDITED"
    elif choice == "3":
        label = "real"
        label_str = "AUTHENTIC / REAL"
    else:
        label = "generated_by_ai"
        label_str = "GENERATED BY AI"

    notes = input(f"{C_CYAN}Enter custom notes / exemplar description (optional): {C_RESET}").strip()

    print(f"\n{C_YELLOW}Extracting 14-engine forensic specs and computing perceptual fingerprints...{C_RESET}")
    start_t = time.time()
    from src.detector import learn_and_register_image
    record = learn_and_register_image(img_path, label=label, notes=notes, force_override=True)
    dur = time.time() - start_t

    print(f"\n{C_GREEN}{C_BOLD}[TRAINING COMPLETE] — IMAGE LOCKED IN PERMANENT MEMORY BANK ({dur:.2f}s){C_RESET}")
    print(f"{C_BOLD}  • Verdict Assigned:{C_RESET}   {record['verdict_label']}")
    print(f"{C_BOLD}  • Human Authenticity:{C_RESET} {record['human_score']}%")
    print(f"{C_BOLD}  • AI Threat Score:{C_RESET}    {record['ai_score']}%")
    print(f"{C_BOLD}  • Archived Dataset:{C_RESET}   {record['dataset_path']}")

    display_specs_card(record["forensic_specs"], title=f"LEARNED SPECS — {os.path.basename(img_path)}")


def match_single_interactive():
    print(f"\n{C_BOLD}{C_CYAN}=== [2] SPEC-MATCH & ANALYZE SUSPECT IMAGE ==={C_RESET}")
    path_raw = input(f"{C_CYAN}Enter image path to test against memory bank: {C_RESET}")
    img_path = clean_input_path(path_raw)

    if not os.path.exists(img_path):
        print(f"{C_RED}[ERROR] File not found: {img_path}{C_RESET}")
        return

    try:
        img = Image.open(img_path).convert("RGB")
    except Exception as e:
        print(f"{C_RED}[ERROR] Could not open image: {e}{C_RESET}")
        return

    print(f"\n{C_YELLOW}Querying memory bank and analyzing forensic specs...{C_RESET}")
    start_t = time.time()
    from src.detector import match_image_against_registry, full_image_analysis
    match_data = match_image_against_registry(img, threshold=75.0)
    dur = time.time() - start_t

    if match_data.get("matched"):
        ex = match_data["exemplar"]
        sim = match_data["similarity"]
        m_type = match_data["match_type"]
        v_label = match_data["trained_verdict_label"]
        v_verdict = match_data["trained_verdict"]

        print(f"\n{C_GREEN}{C_BOLD}╔═══════════════════════════════════════════════════════════════════════════╗{C_RESET}")
        print(f"{C_GREEN}{C_BOLD}║  [TRAINED MEMORY MATCH CONFIRMED]                                      ║{C_RESET}")
        print(f"{C_GREEN}{C_BOLD}║  Match Similarity: {sim:.1f}% ({m_type})                              ║{C_RESET}")
        print(f"{C_GREEN}{C_BOLD}╚═══════════════════════════════════════════════════════════════════════════╝{C_RESET}")

        print(f"\n{C_BOLD}MATCHED EXEMPLAR DETAILS:{C_RESET}")
        print(f"  • Trained Filename:   {C_CYAN}{ex.get('filename')}{C_RESET}")
        print(f"  • Trained SHA-256:    {C_YELLOW}{ex.get('sha256')}{C_RESET}")
        print(f"  • Registered At:      {ex.get('registered_at')}")
        print(f"  • Custom Notes:       {ex.get('notes') or 'N/A'}")
        print(f"  • {C_BOLD}EXACT LEARNED ANSWER:{C_RESET} {C_BOLD}{v_label}{C_RESET} (AI Threat: {ex.get('ai_score')}%, Authenticity: {ex.get('human_score')}%)")

        # Compare specs side by side
        inp_specs = match_data.get("specs", {})
        tgt_specs = ex.get("forensic_specs", {})
        if tgt_specs:
            inp_res_str = f"{inp_specs.get('resolution', {}).get('width', '?')}x{inp_specs.get('resolution', {}).get('height', '?')}"
            tgt_res_str = f"{tgt_specs.get('resolution', {}).get('width', '?')}x{tgt_specs.get('resolution', {}).get('height', '?')}"
            inp_freq = inp_specs.get('frequency_specs', {}).get('high_frequency_ratio', 0)
            tgt_freq = tgt_specs.get('frequency_specs', {}).get('high_frequency_ratio', 0)
            inp_tex = inp_specs.get('texture_specs', {}).get('laplacian_variance', 0)
            tgt_tex = tgt_specs.get('texture_specs', {}).get('laplacian_variance', 0)
            inp_sat = inp_specs.get('color_profile', {}).get('saturation_mean', 0)
            tgt_sat = tgt_specs.get('color_profile', {}).get('saturation_mean', 0)
            inp_noise = inp_specs.get('noise_specs', {}).get('sensor_noise_std', 0)
            tgt_noise = tgt_specs.get('noise_specs', {}).get('sensor_noise_std', 0)

            print(f"\n{C_CYAN}{C_BOLD}┌── [ SPEC COMPARISON TABLE ] ────────────────────────────────────────────{C_RESET}")
            print(f"{C_CYAN}│{C_RESET} {'METRIC':<24} | {'TEST IMAGE':<20} | {'TRAINED EXEMPLAR':<20}")
            print(f"{C_CYAN}│{C_RESET} " + "-" * 68)
            print(f"{C_CYAN}│{C_RESET} {'Resolution':<24} | {inp_res_str:<20} | {tgt_res_str:<20}")
            print(f"{C_CYAN}│{C_RESET} {'FFT High-Freq Ratio':<24} | {inp_freq:<20} | {tgt_freq:<20}")
            print(f"{C_CYAN}│{C_RESET} {'Texture Laplacian':<24} | {inp_tex:<20} | {tgt_tex:<20}")
            print(f"{C_CYAN}│{C_RESET} {'Saturation Mean':<24} | {inp_sat:<20} | {tgt_sat:<20}")
            print(f"{C_CYAN}│{C_RESET} {'Noise Residual STD':<24} | {inp_noise:<20} | {tgt_noise:<20}")
            print(f"{C_CYAN}└────────────────────────────────────────────────────────────────────────{C_RESET}\n")
    else:
        print(f"\n{C_YELLOW}[!] No matching exemplar in trained memory bank (Best Similarity: {match_data.get('similarity', 0.0):.1f}%).{C_RESET}")
        print(f"{C_CYAN}Running full 14-engine multi-domain forensic analysis...{C_RESET}")
        res = full_image_analysis(img)
        print(f"\n{C_BOLD}14-ENGINE ANALYSIS RESULT:{C_RESET}")
        print(f"  • Verdict:          {res['verdict_label']}")
        print(f"  • AI Probability:   {res['confidence_score']:.1f}%")
        print(f"  • Authenticity:     {res['human_score']:.1f}%")
        print(f"  • Forensic Judge:   {res['judge_verdict']} ({res['judge_score']:.1f}/100)")
        display_specs_card(match_data.get("specs", {}), title="EXTRACTED SPECS")


def list_memory_bank():
    reg = _get_cached_registry()
    print(f"\n{C_BOLD}{C_MAGENTA}=== [3] TRAINED FORENSIC MEMORY BANK ({len(reg)} REGISTERED EXEMPLARS) ==={C_RESET}\n")
    if not reg:
        print(f"{C_YELLOW}Memory bank is empty. Use Option 1 to train your first image.{C_RESET}\n")
        return

    print(f"{'#':<3} | {'FILENAME':<24} | {'LABEL':<16} | {'VERDICT':<24} | {'REGISTERED AT':<20}")
    print("-" * 96)
    for idx, (sha, item) in enumerate(reg.items(), 1):
        fn = item.get("filename", "unknown")[:22]
        lbl = item.get("label", "unknown")[:14]
        vrd = item.get("verdict_label", item.get("verdict", "UNKNOWN"))[:22]
        reg_t = item.get("registered_at", "N/A")[:19]
        print(f"{idx:<3} | {fn:<24} | {lbl:<16} | {vrd:<24} | {reg_t:<20}")
    print("-" * 96 + "\n")


def batch_train_interactive():
    print(f"\n{C_BOLD}{C_YELLOW}=== [4] BATCH TRAIN DIRECTORY ==={C_RESET}")
    path_raw = input(f"{C_CYAN}Enter directory path containing images: {C_RESET}")
    folder_path = clean_input_path(path_raw)

    if not os.path.isdir(folder_path):
        print(f"{C_RED}[ERROR] Directory not found: {folder_path}{C_RESET}")
        return

    valid_exts = {".png", ".jpg", ".jpeg", ".webp"}
    files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if Path(f).suffix.lower() in valid_exts]

    if not files:
        print(f"{C_RED}[ERROR] No images found in {folder_path}{C_RESET}")
        return

    print(f"\nFound {len(files)} image(s). Select category for all images in folder:")
    print(f"  {C_RED}[1] GENERATED BY AI{C_RESET}")
    print(f"  {C_YELLOW}[2] AI-EDITED{C_RESET}")
    print(f"  {C_GREEN}[3] AUTHENTIC / REAL{C_RESET}")

    choice = input(f"{C_CYAN}Select option [1-3] (Default 1): {C_RESET}").strip()
    if choice == "2":
        label = "ai_edited"
    elif choice == "3":
        label = "real"
    else:
        label = "generated_by_ai"

    notes = input(f"{C_CYAN}Enter batch tag / notes (optional): {C_RESET}").strip()

    print(f"\n{C_YELLOW}Processing batch training...{C_RESET}")
    from src.detector import learn_and_register_image
    success_count = 0
    for idx, fpath in enumerate(files, 1):
        try:
            print(f"  [{idx}/{len(files)}] Learning {os.path.basename(fpath)}... ", end="", flush=True)
            learn_and_register_image(fpath, label=label, notes=notes, force_override=True)
            print(f"{C_GREEN}DONE{C_RESET}")
            success_count += 1
        except Exception as e:
            print(f"{C_RED}FAILED ({e}){C_RESET}")

    print(f"\n{C_GREEN}{C_BOLD}[BATCH COMPLETE]: Successfully trained {success_count}/{len(files)} image(s).{C_RESET}\n")


def interactive_loop():
    while True:
        print_banner()
        print(f"{C_BOLD}AVAILABLE ACTIONS:{C_RESET}")
        print(f"  {C_MAGENTA}[1]{C_RESET} Train & Remember Single Image (Extract specs + Lock verdict)")
        print(f"  {C_CYAN}[2]{C_RESET} Analyze & Spec-Match Suspect Image Against Memory Bank")
        print(f"  {C_YELLOW}[3]{C_RESET} Batch Train Entire Directory")
        print(f"  {C_GREEN}[4]{C_RESET} View Trained Knowledge Bank")
        print(f"  {C_RED}[5]{C_RESET} Exit")

        choice = input(f"\n{C_BOLD}Enter choice [1-5]: {C_RESET}").strip()
        if choice == "1":
            train_single_interactive()
        elif choice == "2":
            match_single_interactive()
        elif choice == "3":
            batch_train_interactive()
        elif choice == "4":
            list_memory_bank()
        elif choice in ("5", "q", "exit"):
            print(f"\n{C_CYAN}Exiting NEXUS+ Forensic Trainer. Goodbye!{C_RESET}\n")
            break
        else:
            print(f"{C_RED}Invalid option, please choose 1-5.{C_RESET}")
        
        input(f"\n{C_DIM}Press Enter to return to menu...{C_RESET}")


def main():
    parser = argparse.ArgumentParser(description="NEXUS+ Forensic Training & Memory Spec-Matching Tool")
    parser.add_argument("--train", type=str, help="Path to image to train and lock in memory")
    parser.add_argument("--label", type=str, default="generated_by_ai", choices=["generated_by_ai", "ai", "ai_edited", "edited", "real", "authentic"], help="Ground truth label")
    parser.add_argument("--notes", type=str, default="", help="Optional notes/tags for the trained image")
    parser.add_argument("--match", type=str, help="Path to suspect image to analyze and spec-match against memory")
    parser.add_argument("--batch", type=str, help="Path to directory for batch training")
    parser.add_argument("--list", action="store_true", help="List all trained images in memory bank")

    args = parser.parse_args()

    if args.list:
        list_memory_bank()
        return

    if args.train:
        img_path = clean_input_path(args.train)
        if not os.path.exists(img_path):
            print(f"{C_RED}[ERROR] File not found: {img_path}{C_RESET}")
            sys.exit(1)
        from src.detector import learn_and_register_image
        record = learn_and_register_image(img_path, label=args.label, notes=args.notes)
        print(f"{C_GREEN}[SUCCESS] Trained and remembered {os.path.basename(img_path)}{C_RESET}")
        print(f"Verdict: {record['verdict_label']} | SHA: {record['sha256'][:12]} | Dataset: {record['dataset_path']}")
        display_specs_card(record["forensic_specs"], title="LEARNED SPECS")
        return

    if args.match:
        img_path = clean_input_path(args.match)
        if not os.path.exists(img_path):
            print(f"{C_RED}[ERROR] File not found: {img_path}{C_RESET}")
            sys.exit(1)
        img = Image.open(img_path).convert("RGB")
        from src.detector import match_image_against_registry
        match_data = match_image_against_registry(img)
        if match_data.get("matched"):
            ex = match_data["exemplar"]
            print(f"{C_GREEN}[MATCH CONFIRMED] Similarity: {match_data['similarity']:.1f}% ({match_data['match_type']}){C_RESET}")
            print(f"Exemplar: {ex.get('filename')} | Verdict: {match_data['trained_verdict_label']}")
        else:
            print(f"{C_YELLOW}[NO MATCH] Similarity: {match_data.get('similarity', 0.0):.1f}%{C_RESET}")
        return

    if args.batch:
        folder = clean_input_path(args.batch)
        if not os.path.isdir(folder):
            print(f"{C_RED}[ERROR] Directory not found: {folder}{C_RESET}")
            sys.exit(1)
        valid_exts = {".png", ".jpg", ".jpeg", ".webp"}
        files = [os.path.join(folder, f) for f in os.listdir(folder) if Path(f).suffix.lower() in valid_exts]
        from src.detector import learn_and_register_image
        for f in files:
            learn_and_register_image(f, label=args.label, notes=args.notes)
        print(f"{C_GREEN}[SUCCESS] Batch trained {len(files)} images.{C_RESET}")
        return

    # Default to interactive menu
    interactive_loop()


if __name__ == "__main__":
    main()
