"""
retrain_vit.py  --  NEXUS+ ViT Retrainer v2  (Real AI Images + LFW Real Photos)
=================================================================================
Dataset sources:
  REAL  ->  LFW face dataset via sklearn  (5,985 genuine photographic portraits)
  AI    ->  13 images genuinely generated by an AI image model  (core signal)
            + supplementary synthetic PIL samples for volume

Strategy:
  - WeightedRandomSampler gives the 13 real-AI images 5x oversampling weight
    so the model learns the true AI texture fingerprint, not just PIL patterns.
  - 3 fine-tuning epochs on the existing fine_tuned_vit/ checkpoint.
  - Saves updated model + eval_results.json + training_curves.png.

Run:
    .\\venv\\Scripts\\python.exe scripts\\retrain_vit.py
"""

import os, sys, json, random, warnings
from pathlib import Path
import io as _io

# Windows UTF-8 stdout fix
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = _io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    sys.stderr = _io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

warnings.filterwarnings("ignore")

import numpy as np
from PIL import Image, ImageFilter, ImageEnhance, ImageDraw
import torch
from torch.utils.data import Dataset, WeightedRandomSampler, DataLoader
from transformers import (
    ViTForImageClassification,
    ViTImageProcessor,
    TrainingArguments,
    Trainer,
)

# ---------------------------------------------------------------------------
# PATHS
# ---------------------------------------------------------------------------
ROOT        = Path(__file__).resolve().parent.parent
DATASET_DIR = ROOT / "data" / "dataset"
AI_DIR      = DATASET_DIR / "ai"
REAL_DIR    = DATASET_DIR / "real"
MODEL_OUT   = ROOT / os.environ.get("NEXUS_MODEL_OUT", "fine_tuned_vit")
MODEL_IN    = ROOT / os.environ.get("NEXUS_MODEL_IN", "fine_tuned_vit")
BASE_MODEL  = "google/vit-base-patch16-224"

AI_DIR.mkdir(parents=True, exist_ok=True)
REAL_DIR.mkdir(parents=True, exist_ok=True)

IMG_SIZE = 224
# Environment overrides let a feedback refresh complete quickly without
# changing the default full-retraining configuration.
EPOCHS   = int(os.environ.get("NEXUS_TRAIN_EPOCHS", "4"))
BATCH    = int(os.environ.get("NEXUS_TRAIN_BATCH", "8"))
SEED     = 42
random.seed(SEED)
np.random.seed(SEED)


# ---------------------------------------------------------------------------
# STEP 1  --  REAL IMAGES  (LFW dataset -- genuine photographic portraits)
# ---------------------------------------------------------------------------

def load_lfw_real_images(target: int = 150) -> int:
    """Save LFW photographic face images into data/dataset/real/."""
    existing = list(REAL_DIR.glob("lfw_*.jpg"))
    if len(existing) >= target:
        print(f"[LFW] {len(existing)} LFW photos already in dataset.")
        return len(existing)

    print(f"[LFW] Loading LFW face dataset from sklearn cache ...")
    try:
        from sklearn.datasets import fetch_lfw_people
        # min_faces_per_person=1 gives us the full 13,233 images
        lfw = fetch_lfw_people(min_faces_per_person=1, resize=1.0, color=True,
                               download_if_missing=True)
        images = lfw.images   # (N, H, W, 3) float32  0..1 or 0..255

        if images.max() <= 1.0:
            imgs_u8 = (images * 255).clip(0, 255).astype(np.uint8)
        else:
            imgs_u8 = images.astype(np.uint8)

        indices = list(range(len(imgs_u8)))
        random.shuffle(indices)

        saved = 0
        for i in indices:
            if saved >= target:
                break
            out = REAL_DIR / f"lfw_{i:05d}.jpg"
            if out.exists():
                saved += 1
                continue
            img = Image.fromarray(imgs_u8[i]).convert("RGB")
            img = img.resize((IMG_SIZE, IMG_SIZE), Image.LANCZOS)
            # Slight unsharp mask to mimic camera lens sharpness
            img = img.filter(ImageFilter.UnsharpMask(radius=1, percent=110, threshold=3))
            img.save(str(out), "JPEG", quality=int(random.uniform(88, 95)))
            saved += 1

        total = len(list(REAL_DIR.glob("lfw_*.jpg")))
        print(f"[LFW] {saved} LFW photos saved  (total in folder: {total})")
        return total

    except Exception as exc:
        print(f"[LFW] ERROR: {exc}")
        print("[LFW] Falling back to synthetic photographic portraits...")
        return generate_synthetic_real(target)


def generate_synthetic_real(n: int = 150) -> int:
    """Photographic-style portraits with sensor noise as real-class fallback."""
    existing = list(REAL_DIR.glob("synth_real_*.jpg"))
    if len(existing) >= n:
        print(f"[SynthReal] {len(existing)} synthetic real images already present.")
        return len(existing)

    skin_tones = [
        (210,170,135),(240,195,160),(185,140,105),(150,105,80),
        (120,75,55),(230,185,150),(200,155,120),(245,210,180),
    ]
    jacket_colors = [
        (80,90,75),(50,60,80),(30,30,30),(120,100,80),
        (180,60,60),(60,80,110),(100,90,85),
    ]
    saved = 0
    for i in range(n):
        out = REAL_DIR / f"synth_real_{i:04d}.jpg"
        if out.exists():
            saved += 1
            continue
        skin   = random.choice(skin_tones)
        jacket = random.choice(jacket_colors)
        bg     = (random.randint(60,180), random.randint(60,160), random.randint(50,140))

        arr = np.random.randint(
            [bg[0]-25, bg[1]-25, bg[2]-25],
            [bg[0]+25, bg[1]+25, bg[2]+25],
            (IMG_SIZE, IMG_SIZE, 3), dtype=np.int32).clip(0,255).astype(np.uint8)
        img = Image.fromarray(arr).filter(ImageFilter.GaussianBlur(7))

        draw = ImageDraw.Draw(img)
        cx = random.randint(100, 125)
        cy = random.randint(60, 80)
        draw.ellipse([cx-46, cy-55, cx+46, cy+55], fill=skin)
        draw.ellipse([cx-47, cy-68, cx+47, cy-28], fill=(25,18,12))

        ey = cy - random.randint(8, 16)
        for ex in [cx - random.randint(14,20), cx + random.randint(14,20)]:
            draw.ellipse([ex-5, ey-4, ex+5, ey+4], fill=(22,18,12))

        draw.rectangle([random.randint(45,65), 130,
                        random.randint(155,180), IMG_SIZE], fill=jacket)

        # Sensor noise (photographic grain -- distinguishes real from AI)
        arr2 = np.array(img, dtype=np.float32)
        arr2 += np.random.normal(0, random.uniform(7, 14), arr2.shape)
        arr2 = np.clip(arr2, 0, 255).astype(np.uint8)
        img = Image.fromarray(arr2)

        img = ImageEnhance.Contrast(img).enhance(random.uniform(0.88, 1.12))
        img.save(str(out), "JPEG", quality=random.randint(85, 94))
        saved += 1

    total = len(list(REAL_DIR.glob("synth_real_*.jpg")))
    print(f"[SynthReal] Generated {saved} new synthetic real images (total: {total})")
    return total


# ---------------------------------------------------------------------------
# STEP 2  --  AI IMAGES  (genuine AI + supplementary synthetic)
# ---------------------------------------------------------------------------

def ensure_ai_dataset(target: int = 130) -> list:
    """
    Returns list of (path, weight) for all AI samples.
    - Genuinely AI-generated images (genai_*.jpg) get weight=5.0
    - Older synthetic PIL images get weight=1.0
    """
    # Check for genuinely AI-generated images (copied from generate_image artifacts)
    genuine_ai = sorted(AI_DIR.glob("genai_*.jpg"))
    print(f"[AI Dataset] Genuine AI-generated images: {len(genuine_ai)}")

    all_ai = sorted(AI_DIR.glob("*.jpg")) + sorted(AI_DIR.glob("*.png"))
    if len(all_ai) < target:
        needed = target - len(all_ai)
        print(f"[AI Dataset] Generating {needed} supplementary synthetic AI samples...")
        _generate_supplementary_ai(needed)

    # Build weighted list: genuine AI = 5x weight
    genuine_set   = {str(p) for p in genuine_ai}
    hyperreal_set = {str(p) for p in AI_DIR.glob("hyperreal_ai_*.jpg")}
    weighted = []
    for p in sorted(AI_DIR.glob("*.jpg")) + sorted(AI_DIR.glob("*.png")):
        ps = str(p)
        if ps in genuine_set:
            w = 5.0   # genuinely AI-generated: highest weight
        elif ps in hyperreal_set:
            w = 4.0   # ultra-realistic computational: high weight (hardest negatives)
        else:
            w = 1.0   # older simple synthetic: baseline
        weighted.append((ps, w))

    print(f"[AI Dataset] Total AI samples: {len(weighted)}  "
          f"(genuine: {len(genuine_ai)}, synthetic: {len(weighted)-len(genuine_ai)})")
    return weighted


def _generate_supplementary_ai(n: int):
    """Generate PIL-based AI-lookalike images (smooth, saturated, no noise)."""
    styles = ["midjourney", "sdxl", "dalle", "studio", "diffusion"]
    count = len(list(AI_DIR.glob("synth_ai_*.jpg")))

    for i in range(n):
        out = AI_DIR / f"synth_ai_{count+i:05d}.jpg"
        if out.exists():
            continue
        style = random.choice(styles)
        skin = (random.randint(215,245), random.randint(180,210), random.randint(155,185))

        if style in ("midjourney", "sdxl"):
            bg_col = (random.randint(20,60), random.randint(20,60), random.randint(40,90))
            img = Image.new("RGB", (IMG_SIZE, IMG_SIZE), bg_col)
            draw = ImageDraw.Draw(img)
            draw.ellipse([38, 28, 186, 196], fill=skin)
            img = img.filter(ImageFilter.GaussianBlur(random.uniform(5, 8)))
            draw = ImageDraw.Draw(img)
            for ex in [75, 148]:
                draw.ellipse([ex, 88, ex+22, 110], fill=(22,18,12))
            draw.arc([82, 148, 142, 168], start=10, end=170, fill=(155,60,65), width=3)
            img = img.filter(ImageFilter.SMOOTH_MORE).filter(ImageFilter.SMOOTH_MORE)
        elif style == "dalle":
            arr = np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8)
            for c, base in enumerate([random.randint(200,255),
                                       random.randint(150,220),
                                       random.randint(180,240)]):
                arr[:,:,c] = np.linspace(base-40, base, IMG_SIZE, dtype=np.uint8)
            img = Image.fromarray(arr).filter(ImageFilter.GaussianBlur(3))
            ImageDraw.Draw(img).ellipse([50,40,174,184], fill=skin)
            img = img.filter(ImageFilter.SMOOTH)
        else:
            img = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (28,22,45))
            ImageDraw.Draw(img).ellipse([35,25,189,199], fill=skin)
            img = img.filter(ImageFilter.GaussianBlur(random.uniform(5,9)))

        # No sensor noise for AI (smooth = AI trait)
        img = ImageEnhance.Color(img).enhance(random.uniform(1.2, 1.7))
        img.save(str(out), "JPEG", quality=97)


# ---------------------------------------------------------------------------
# STEP 3  --  DATASET
# ---------------------------------------------------------------------------

class AIDetectorDataset(Dataset):
    def __init__(self, samples, processor, augment=False):
        # samples: list of (path_str, label_int)
        self.samples   = samples
        self.processor = processor
        self.augment   = augment

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        path, label = self.samples[idx]
        try:
            img = Image.open(path).convert("RGB").resize((IMG_SIZE, IMG_SIZE), Image.LANCZOS)
        except Exception:
            img = Image.new("RGB", (IMG_SIZE, IMG_SIZE), (128,128,128))

        if self.augment:
            if random.random() > 0.5:
                img = img.transpose(Image.FLIP_LEFT_RIGHT)
            img = ImageEnhance.Brightness(img).enhance(random.uniform(0.85, 1.15))
            img = ImageEnhance.Contrast(img).enhance(random.uniform(0.88, 1.12))
            angle = random.uniform(-12, 12)
            img = img.rotate(angle, fillcolor=(128,128,128))

        pixel_values = self.processor(images=img, return_tensors="pt")["pixel_values"].squeeze(0)
        return {"pixel_values": pixel_values,
                "labels": torch.tensor(label, dtype=torch.long)}


# ---------------------------------------------------------------------------
# STEP 4  --  TRAIN
# ---------------------------------------------------------------------------

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    # Avoid `evaluate.load("accuracy")`: it obtains a global Hugging Face cache
    # lock, which can be unavailable in a sandboxed desktop session.
    return {"accuracy": float(np.mean(preds == labels))}


def train():
    print("\n" + "=" * 62)
    print("  NEXUS+ ViT Retrainer v2")
    print("  Real images: LFW face dataset (genuine photography)")
    print("  AI images  : Genuinely AI-generated portraits + synthetic")
    print("=" * 62)

    # 1. Build real dataset
    n_real = load_lfw_real_images(target=150)
    if n_real < 30:
        generate_synthetic_real(150)

    # 2. Build AI dataset (weighted)
    ai_weighted = ensure_ai_dataset(target=130)

    # 3. Collect all samples with labels
    # Include JPEG uploads as well as .jpg/.png files. User feedback arrives
    # through the UI in its original extension, which is commonly `.jpeg`.
    real_paths = (
        sorted(REAL_DIR.glob("*.jpg"))
        + sorted(REAL_DIR.glob("*.jpeg"))
        + sorted(REAL_DIR.glob("*.png"))
    )
    # (path, label, sample_weight)
    all_samples = [(str(p), 1, 1.0) for p in real_paths]          # label 1 = real
    for (p, w) in ai_weighted:
        all_samples.append((p, 0, w))                              # label 0 = AI

    random.shuffle(all_samples)
    split = int(len(all_samples) * 0.8)
    train_raw = all_samples[:split]
    val_raw   = all_samples[split:]

    # A user-labelled feedback image must influence training, not merely be
    # held out for evaluation by the random split.
    feedback_val = [s for s in val_raw if Path(s[0]).name.startswith("feedback_")]
    if feedback_val:
        val_raw = [s for s in val_raw if s not in feedback_val]
        train_raw.extend(feedback_val)
        random.shuffle(train_raw)

    # 5x oversample real feedback photos (selfies/camera photos) to teach the model
    # mobile ISP denoising, lighting and focal geometry of genuine camera photos
    feedback_train = [s for s in train_raw if Path(s[0]).name.startswith("feedback_")]
    for _ in range(4):
        train_raw.extend(feedback_train)
    random.shuffle(train_raw)

    train_samples = [(p, lbl) for p, lbl, _ in train_raw]
    val_samples   = [(p, lbl) for p, lbl, _ in val_raw]
    train_weights = [w for _, _, w in train_raw]

    print(f"\n[Dataset]  Real: {len(real_paths)}   AI: {len(ai_weighted)}")
    print(f"[Split]    Train: {len(train_samples)}   Val: {len(val_samples)}")
    genuine_count = sum(1 for p, lbl, _ in train_raw if lbl == 0 and 'genai_' in p)
    print(f"[AI Core]  Genuine AI-generated images in train split: {genuine_count}")

    # 4. Load from checkpoint
    existing_ckpt = MODEL_IN / "model.safetensors"
    start_from = str(MODEL_IN) if existing_ckpt.exists() else BASE_MODEL
    print(f"\n[Model] Loading checkpoint: {start_from}")

    processor = ViTImageProcessor.from_pretrained(start_from)
    model = ViTForImageClassification.from_pretrained(
        start_from,
        num_labels=2,
        id2label={0: "artificial", 1: "real"},
        label2id={"artificial": 0, "real": 1},
        ignore_mismatched_sizes=True,
    )

    # 5. Datasets
    train_ds = AIDetectorDataset(train_samples, processor, augment=True)
    val_ds   = AIDetectorDataset(val_samples,   processor, augment=False)

    # 6. Training args
    args = TrainingArguments(
        output_dir                  = str(MODEL_OUT),
        num_train_epochs            = EPOCHS,
        per_device_train_batch_size = BATCH,
        per_device_eval_batch_size  = BATCH,
        eval_strategy               = "epoch",
        save_strategy               = "epoch",
        logging_steps               = 5,
        load_best_model_at_end      = True,
        metric_for_best_model       = "accuracy",
        learning_rate               = 2e-5,
        weight_decay                = 0.01,
        warmup_steps                = 20,
        fp16                        = False,
        dataloader_num_workers      = 0,
        remove_unused_columns       = False,
        report_to                   = "none",
        seed                        = SEED,
    )

    trainer = Trainer(
        model           = model,
        args            = args,
        train_dataset   = train_ds,
        eval_dataset    = val_ds,
        compute_metrics = compute_metrics,
    )

    print(f"\n[Training] {EPOCHS} epochs | {len(train_ds)} train samples")
    print("[Training] Running ... (10-25 min on CPU)\n")
    trainer.train()

    # 7. Evaluate
    ev  = trainer.evaluate()
    acc  = ev.get("eval_accuracy", 0.0)
    loss = ev.get("eval_loss", 0.0)
    print(f"\n[Results] Accuracy: {acc*100:.2f}%   Loss: {loss:.4f}")

    # 8. Save
    trainer.save_model(str(MODEL_OUT))
    processor.save_pretrained(str(MODEL_OUT))

    json.dump({
        "eval_accuracy":         round(acc, 4),
        "eval_loss":             round(loss, 6),
        "train_samples":         len(train_samples),
        "val_samples":           len(val_samples),
        "epochs":                EPOCHS,
        "base_model":            BASE_MODEL,
        "real_source":           "LFW face dataset (sklearn)",
        "ai_source":             "Genuine AI-generated images + synthetic PIL",
        "genuine_ai_images":     len(list(AI_DIR.glob("genai_*.jpg"))),
        "real_portrait_training": True,
    }, open(MODEL_OUT / "eval_results.json", "w"), indent=2)

    # 9. Training curves
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt

        hist = trainer.state.log_history
        t_loss = [(h["epoch"], h["loss"]) for h in hist if "loss" in h and "eval_loss" not in h]
        e_acc  = [(h["epoch"], h["eval_accuracy"]) for h in hist if "eval_accuracy" in h]

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
        fig.patch.set_facecolor("#070A18")
        for ax, data, title, color in [
            (ax1, t_loss, "Training Loss",       "#8B5CF6"),
            (ax2, e_acc,  "Validation Accuracy", "#2ED573"),
        ]:
            if data:
                ax.plot([d[0] for d in data], [d[1] for d in data],
                        color=color, linewidth=2.5, marker="o", markersize=5)
            ax.set_title(title, color="white", fontsize=13, pad=8)
            ax.set_facecolor("#0D1120")
            ax.tick_params(colors="white")
            for spine in ax.spines.values():
                spine.set_edgecolor("#2a2a3a")
        plt.tight_layout(pad=2)
        plt.savefig(str(MODEL_OUT / "training_curves.png"),
                    dpi=130, bbox_inches="tight", facecolor=fig.get_facecolor())
        plt.close()
        print("[Plot] Saved training_curves.png")
    except Exception as e:
        print(f"[Plot] Skipped: {e}")

    print("\n" + "=" * 62)
    print("  RETRAINING COMPLETE")
    print(f"  Accuracy : {acc*100:.2f}%")
    print(f"  Model    : fine_tuned_vit/")
    print("=" * 62)
    print("\nRestart streamlit to activate the updated Engine 11.")


if __name__ == "__main__":
    train()
