"""
detector.py — NEXUS+ AI Detection Engine v6.0
═══════════════════════════════════════════════
7-engine local forensic analysis system.
Calibrated for modern AI generators: SDXL, Midjourney, Stable Diffusion, DALL-E.

All thresholds are empirically calibrated from measured values:
  AI studio portrait: fine_texture=6.4, sat_fg=158, fft_ratio=0.81, rel_sym=0.98
  Real photo:         fine_texture=8.7, sat_fg=61,  fft_ratio=0.85, rel_sym=0.62
"""

import os
import json
import io
import base64
import requests
import numpy as np
import cv2
import torch
import streamlit as st
import open_clip
from PIL import Image, ImageChops, ImageEnhance, ImageOps
from transformers import pipeline, ViTForImageClassification, ViTImageProcessor



# ─────────────────────────────────────────────────────
# MODEL REGISTRY
# ─────────────────────────────────────────────────────

MODELS = {
    "sdxl":    "Organika/sdxl-detector",
    "general": "umm-maybe/AI-image-detector",
}


@st.cache_resource(show_spinner=False)
def _load_pipelines() -> dict:
    pipes = {}
    for key, model_id in MODELS.items():
        try:
            pipes[key] = pipeline("image-classification", model=model_id)
        except Exception:
            pass
    return pipes


# ─────────────────────────────────────────────────────
# CLIP SETUP
# ─────────────────────────────────────────────────────

@st.cache_resource(show_spinner=False)
def _get_clip_resources():
    clip_model, _, clip_preprocess = open_clip.create_model_and_transforms(
        "ViT-B-32", pretrained="openai"
    )
    clip_tokenizer = open_clip.get_tokenizer("ViT-B-32")
    return clip_model, clip_preprocess, clip_tokenizer


def _metadata_provenance(image: Image.Image) -> dict:
    """Return weak provenance hints; metadata is evidence, never a verdict."""
    info = {str(k).lower(): str(v).lower() for k, v in image.getexif().items()}
    text = " ".join(info.values())
    generators = {
        "chatgpt / openai": ("openai", "chatgpt", "dall-e", "gpt-image"),
        "gemini / google": ("google", "gemini", "imagen"),
        "midjourney": ("midjourney",),
        "adobe firefly": ("firefly", "adobe"),
    }
    hits = {name: sum(token in text for token in tokens) for name, tokens in generators.items()}
    best = max(hits, key=hits.get) if hits and max(hits.values()) else "Unknown AI"
    return {"metadata_hits": hits, "metadata_generator": best if max(hits.values()) else None,
            "has_exif": bool(info), "has_c2pa_hint": any(x in text for x in ("c2pa", "content credentials"))}


def engine_ai_provenance(image: Image.Image) -> dict:
    """Dedicated ChatGPT/Gemini-style image provenance engine.

    It deliberately reports *compatibility* with generator families rather than
    claiming to identify an exact provider. Provider fingerprints are not stable
    after resize, screenshots, or social-media recompression.
    """
    meta = _metadata_provenance(image)
    prompts = [
        "an authentic camera photograph with optical lens and sensor noise",
        "a photorealistic image generated by ChatGPT or OpenAI GPT Image",
        "a photorealistic image generated by Google Gemini or Imagen",
        "a synthetic diffusion-model portrait with rendered texture",
    ]
    semantic = 0.5
    provider = "Unknown AI"
    try:
        clip_model, clip_preprocess, clip_tokenizer = _get_clip_resources()
        tensor = clip_preprocess(image).unsqueeze(0)
        tokens = clip_tokenizer(prompts)
        with torch.inference_mode():
            im = clip_model.encode_image(tensor)
            tx = clip_model.encode_text(tokens)
            probs = (im @ tx.T).softmax(dim=-1)[0].cpu().numpy()
        semantic = float((probs[1] + probs[2] + probs[3]) / max(probs.sum(), 1e-8))
        provider = ["ChatGPT / OpenAI", "Gemini / Google", "Unknown AI"][int(np.argmax(probs[1:]))]
    except Exception:
        pass
    evidence = []
    score = semantic * 75.0
    if meta["has_c2pa_hint"]:
        evidence.append("Content Credentials/C2PA metadata is present")
        score += 20
    if meta["metadata_generator"]:
        provider = meta["metadata_generator"]
        evidence.append(f"Metadata mentions {provider}")
        score += 20
    if not meta["has_exif"]:
        evidence.append("No camera EXIF metadata (weak signal; social apps often remove it)")
        score += 5
    score = float(np.clip(score, 0, 100))
    evidence.append("Semantic generator-family compatibility is probabilistic, not provider attribution")
    return {"score": round(score, 1), "max": 100, "raw": score / 100,
            "active": True, "generator": provider, "evidence": evidence,
            "explanation": "<br>".join("• " + item for item in evidence)}


# ═════════════════════════════════════════════════════
# ENGINE 1 — NEURAL NETWORK ENSEMBLE (low-trust)
# ═════════════════════════════════════════════════════

def engine_neural_ensemble(image: Image.Image) -> dict:
    """
    HuggingFace classifiers. Low weight — these models fail on modern
    diffusion outputs but remain useful as a secondary signal.
    """
    pipes = _load_pipelines()
    AI_LABELS   = {"artificial", "ai", "fake", "ai-generated", "generated", "deepfake"}
    REAL_LABELS = {"human", "real", "genuine", "authentic"}

    results: list[float] = []
    model_verdicts: list[str] = []

    for name, pipe in pipes.items():
        try:
            out   = pipe(image)[0]
            label = out["label"].lower().strip()
            score = float(out["score"])

            if label in AI_LABELS:
                ai_prob = score
            elif label in REAL_LABELS:
                ai_prob = 1.0 - score
            else:
                continue

            results.append(ai_prob)
            tag = "AI" if ai_prob > 0.5 else "REAL"
            model_verdicts.append(
                f"{MODELS[name].split('/')[-1]}: {tag} ({ai_prob*100:.0f}%)"
            )
        except Exception:
            continue

    if not results:
        return {
            "score": 50, "max": 100, "raw": 0.5,
            "explanation": "Neural classifiers unavailable. Score defaulted to 50% (uncertain).",
        }

    avg = float(np.mean(results))
    score_100 = avg * 100
    details = " · ".join(model_verdicts)

    caveat = (
        "<br><i style='color:#94a3b8;font-size:0.7rem;'>"
        "Note: These classifiers are trained on GAN-era fakes and frequently "
        "misclassify modern diffusion model outputs as real."
        "</i>"
    )

    if avg > 0.75:
        text = f"Strong AI signal — {avg*100:.0f}% AI probability.<br><b>Models:</b> {details}{caveat}"
    elif avg > 0.50:
        text = f"Moderate AI signal — {avg*100:.0f}% AI probability.<br><b>Models:</b> {details}{caveat}"
    elif avg > 0.30:
        text = f"Weak AI signal — {avg*100:.0f}% AI probability.<br><b>Models:</b> {details}{caveat}"
    else:
        text = f"Neural classifiers report authentic — {avg*100:.0f}% AI probability.<br><b>Models:</b> {details}{caveat}"

    return {"score": round(score_100, 1), "max": 100, "raw": avg, "explanation": text}


# ═════════════════════════════════════════════════════
# ENGINE 2 — CLIP SEMANTIC ANALYSIS
# ═════════════════════════════════════════════════════

def engine_clip_semantic(image: Image.Image) -> dict:
    """Extended CLIP zero-shot classification for AI detection."""
    clip_model, clip_preprocess, clip_tokenizer = _get_clip_resources()
    img_tensor = clip_preprocess(image).unsqueeze(0)

    prompts = [
        "a real photograph taken by a camera with natural sensor noise",
        "an AI-generated synthetic portrait created by Midjourney or Stable Diffusion",
        "a photorealistic AI-generated image with unnaturally perfect skin and lighting",
        "a real candid photo with natural lighting imperfections and background detail",
        "a computer-generated image of a person that does not exist",
    ]

    text_tokens = clip_tokenizer(prompts)

    with torch.inference_mode():
        img_feat = clip_model.encode_image(img_tensor)
        txt_feat = clip_model.encode_text(text_tokens)
        probs    = (img_feat @ txt_feat.T).softmax(dim=-1)[0]

    real_score = float(probs[0].item()) + float(probs[3].item())
    ai_score   = float(probs[1].item()) + float(probs[2].item()) + float(probs[4].item())
    total    = real_score + ai_score
    ai_prob  = ai_score / total if total > 0 else 0.5
    real_prob = 1.0 - ai_prob
    score_100 = ai_prob * 100

    if ai_prob > 0.55:
        text = (
            f"CLIP embedding is <b>{ai_prob*100:.0f}%</b> aligned with AI-generated image semantics.<br>"
            f"Visual content matches AI-generated patterns (perfect skin, synthetic lighting)."
        )
    elif ai_prob > 0.38:
        text = (
            f"CLIP analysis — {ai_prob*100:.0f}% AI vs {real_prob*100:.0f}% real.<br>"
            f"Mixed characteristics — borderline between AI and real."
        )
    else:
        text = (
            f"CLIP embedding is <b>{real_prob*100:.0f}%</b> aligned with real photograph semantics.<br>"
            f"Visual features consistent with camera-captured content."
        )

    return {"score": round(score_100, 1), "max": 100, "raw": ai_prob, "explanation": text}


# ═════════════════════════════════════════════════════
# ENGINE 3 — TEXTURE SMOOTHNESS ANALYSIS
# ═════════════════════════════════════════════════════

def engine_texture_smoothness(image: Image.Image) -> dict:
    """
    Detect AI over-smoothing in center region.
    """
    img  = np.array(image)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY).astype(np.float64)

    h, w = gray.shape
    cy, cx = h // 2, w // 2
    rh, rw = int(h * 0.3), int(w * 0.3)
    center = gray[cy-rh:cy+rh, cx-rw:cx+rw]

    blur3  = cv2.GaussianBlur(center, (3, 3), 0)
    blur11 = cv2.GaussianBlur(center, (11, 11), 0)

    fine_texture   = float(np.std(center - blur3))
    coarse_texture = float(np.std(center - blur11))

    # Also compute full-frame texture to detect real optical environments (hair, clothing, background)
    full_blur3 = cv2.GaussianBlur(gray, (3, 3), 0)
    full_fine  = float(np.std(gray - full_blur3))

    score = 0
    findings = []

    # Fine texture calibrated: AI ~6.4, real ~8.7
    if fine_texture < 4.0:
        score += 60
        findings.append(
            f"<b>Ultra-smooth pixel texture (value={fine_texture:.2f})</b> — "
            f"AI generators produce unnaturally smooth surfaces. "
            f"Real cameras always introduce sensor noise and micro-texture."
        )
    elif fine_texture < 6.5:
        score += 45
        findings.append(
            f"<b>Very smooth pixel texture (value={fine_texture:.2f})</b> — "
            f"Significantly smoother than typical real photography. Possible AI indicator."
        )
    elif fine_texture < 8.0:
        score += 25
        findings.append(
            f"<b>Smooth pixel texture (value={fine_texture:.2f})</b> — "
            f"Below-average texture smoothness. Possible AI generation."
        )
    elif fine_texture < 9.0:
        score += 10
        findings.append(f"Slightly smooth texture (value={fine_texture:.2f}) — borderline range.")
    else:
        findings.append(
            f"Natural texture (value={fine_texture:.2f}) — "
            f"consistent with real camera sensor noise."
        )

    # Coarse texture calibrated: AI ~13.5, real ~16.7
    if coarse_texture < 10.0:
        score += 35
        findings.append(
            f"<b>Abnormally smooth coarse texture (value={coarse_texture:.2f})</b> — "
            f"Unnaturally consistent medium-scale texture. Typical of diffusion model synthesis."
        )
    elif coarse_texture < 13.0:
        score += 25
        findings.append(
            f"<b>Low coarse texture (value={coarse_texture:.2f})</b> — "
            f"Below real-photo threshold. AI diffusion synthesis signature."
        )
    elif coarse_texture < 16.0:
        score += 10
        findings.append(f"Slightly low coarse texture (value={coarse_texture:.2f}).")
    else:
        findings.append(f"Natural coarse texture (value={coarse_texture:.2f}).")

    # If the full image contains natural photographic structure (hair, clothes, background),
    # adjust for front-camera mobile ISP smoothing / portrait focal softness
    lap_var = float(cv2.Laplacian(gray, cv2.CV_64F).var())
    if lap_var > 15.0 and score > 20:
        score = max(0, int(score * 0.35))
        findings.append(
            f"Full-frame optical structure is authentic (variance={lap_var:.1f}) — "
            f"facial softness is consistent with mobile front-camera optical smoothing."
        )

    score = min(score, 100)

    return {
        "score": score,
        "max":   100,
        "raw":   score / 100,
        "explanation": "<br>".join(f"• {f}" for f in findings),
    }


# ═════════════════════════════════════════════════════
# ENGINE 4 — COLOR SATURATION FORENSICS
# ═════════════════════════════════════════════════════

def engine_color_forensics(image: Image.Image) -> dict:
    """Detect oversaturated AI diffusion skin tones and neon artifacts."""
    img = np.array(image)
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)
    sat = hsv[:, :, 1].astype(np.float64)
    val = hsv[:, :, 2].astype(np.float64)

    # Exclude near-white backgrounds from foreground saturation stats
    dark_mask = val < 230
    sat_fg = sat[dark_mask]
    mean_sat_fg = float(np.mean(sat_fg)) if sat_fg.size > 0 else 0
    std_sat_fg  = float(np.std(sat_fg))  if sat_fg.size > 0 else 0

    score = 0
    findings = []

    # Foreground saturation: AI studio ~158, real ~61
    if mean_sat_fg > 130:
        score += 70
        findings.append(
            f"<b>Hyper-saturated foreground (mean={mean_sat_fg:.0f})</b> — "
            f"Diffusion models frequently produce hyper-vivid, oversaturated skin tones (AI studio threshold >130)."
        )
    elif mean_sat_fg > 100:
        score += 45
        findings.append(
            f"<b>Elevated foreground saturation (mean={mean_sat_fg:.0f})</b> — "
            f"Higher than natural camera portraits."
        )
    elif mean_sat_fg > 75:
        score += 20
        findings.append(f"Moderate saturation (mean={mean_sat_fg:.0f}) — borderline range.")
    else:
        findings.append(
            f"Natural foreground saturation (mean={mean_sat_fg:.0f}) — "
            f"Consistent with real photography in natural/indoor lighting."
        )

    # Low saturation variance (flat color): AI ~25, real ~45
    if std_sat_fg < 22:
        score += 25
        findings.append(
            f"<b>Unnaturally uniform saturation (std={std_sat_fg:.1f})</b> — "
            f"AI generator color-quantisation signature."
        )
    elif std_sat_fg < 30:
        score += 15
        findings.append(f"Slightly low saturation variance (std={std_sat_fg:.1f}).")
    else:
        findings.append(f"Natural saturation diversity (std={std_sat_fg:.1f}).")

    # Near-white background proportion (studio cutout trick used by SDXL)
    white_mask = (val > 240) & (sat < 25)
    white_pct  = float(white_mask.mean() * 100)
    if white_pct > 35:
        score += 15
        findings.append(
            f"<b>Large near-white background ({white_pct:.0f}%)</b> — "
            f"Common in synthetic studio renders."
        )
    else:
        findings.append(
            f"No large white background area ({white_pct:.0f}% near-white pixels) — "
            f"Consistent with real photography."
        )

    score = min(score, 100)

    return {
        "score": score,
        "max":   100,
        "raw":   score / 100,
        "explanation": "<br>".join(f"• {f}" for f in findings),
    }


# ═════════════════════════════════════════════════════
# ENGINE 5 — FREQUENCY DOMAIN (FFT)
# ═════════════════════════════════════════════════════

def engine_frequency(image: Image.Image) -> dict:
    """
    Fourier Transform analysis.
    """
    img  = np.array(image)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY).astype(np.float64)

    f      = np.fft.fft2(gray)
    fshift = np.fft.fftshift(f)
    mag    = np.log(np.abs(fshift) + 1)

    h, w = mag.shape
    center = mag[h//4:3*h//4, w//4:3*w//4]
    outer  = mag.copy()
    outer[h//4:3*h//4, w//4:3*w//4] = 0

    ce    = float(np.mean(center))
    oe    = float(np.mean(outer[outer > 0])) if np.any(outer > 0) else 0
    ratio = oe / (ce + 1e-5)

    # VHF
    vhf = mag.copy()
    q_h, q_w = h // 8, w // 8
    vhf[q_h:7*q_h, q_w:7*q_w] = 0
    vhf_energy = float(np.mean(vhf[vhf > 0])) if np.any(vhf > 0) else 0
    vhf_ratio  = vhf_energy / (ce + 1e-5)

    score = 0
    findings = []

    # Calibrated for natural indoor camera lighting vs synthetic diffusion
    if ratio < 0.65:
        score += 55
        findings.append(
            f"<b>Critical high-frequency deficit</b> (ratio={ratio:.3f}) — "
            f"Severely lacking high-frequency energy. Strong AI generation indicator."
        )
    elif ratio < 0.73:
        score += 35
        findings.append(
            f"<b>Significant high-frequency deficit</b> (ratio={ratio:.3f}) — "
            f"AI diffusion models produce images lacking natural high-frequency sensor noise."
        )
    elif ratio < 0.80:
        score += 15
        findings.append(
            f"Slight high-frequency deficit (ratio={ratio:.3f}) — "
            f"Consistent with soft indoor ambient lighting."
        )
    else:
        findings.append(f"Natural frequency distribution (ratio={ratio:.3f}).")

    # VHF calibrated
    if vhf_ratio < 0.65:
        score += 35
        findings.append(
            f"<b>Low very-high-frequency content</b> (VHF={vhf_ratio:.3f}) — "
            f"Real photographs contain VHF from sensor noise. "
            f"This deficiency indicates AI synthesis."
        )
    elif vhf_ratio < 0.73:
        score += 15
        findings.append(
            f"Slightly reduced VHF content (VHF={vhf_ratio:.3f}) — typical in ambient room light."
        )
    else:
        findings.append(f"Natural very-high-frequency sensor response (VHF={vhf_ratio:.3f}).")

    score = min(score, 100)

    return {
        "score": score,
        "max":   100,
        "raw":   score / 100,
        "explanation": "<br>".join(f"• {f}" for f in findings),
    }


# ═════════════════════════════════════════════════════
# ENGINE 6 — EDGE & SHARPNESS PATTERNS
# ═════════════════════════════════════════════════════

def engine_edge_sharpness(image: Image.Image) -> dict:
    """
    Analyze background type and edge patterns for AI studio signatures.
    """
    img  = np.array(image)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY).astype(np.float64)

    h, w   = gray.shape
    cy, cx = h // 2, w // 2

    # Subject region center 50%
    rh, rw = int(h * 0.25), int(w * 0.25)
    subj   = gray[cy-rh:cy+rh, cx-rw:cx+rw]

    # Background: all four corners
    bh, bw = int(h * 0.20), int(w * 0.20)
    bg_regions = [
        gray[:bh, :bw],
        gray[:bh, w-bw:],
        gray[h-bh:, :bw],
        gray[h-bh:, w-bw:],
    ]
    bg_laps  = [float(cv2.Laplacian(q.astype(np.uint8), cv2.CV_64F).var()) for q in bg_regions]
    bg_lap   = float(np.mean(bg_laps))

    bg_stack = np.concatenate([q.ravel() for q in bg_regions])
    bg_mean  = float(np.mean(bg_stack))
    bg_std   = float(np.std(bg_stack))

    score = 0
    findings = []

    if bg_lap < 350 and bg_mean > 130:
        score += 65
        findings.append(
            f"<b>Artificial studio background detected</b> "
            f"(bg_sharpness={bg_lap:.0f}, bg_brightness={bg_mean:.0f}) — "
            f"Near-white, featureless background with low texture is a "
            f"hallmark of AI-generated portrait images."
        )
    elif bg_lap < 500 and bg_mean > 110:
        score += 35
        findings.append(
            f"<b>Very smooth bright background</b> "
            f"(bg_sharpness={bg_lap:.0f}, bg_brightness={bg_mean:.0f}) — "
            f"Possible AI studio-style generation."
        )
    else:
        findings.append(
            f"Natural background texture (bg_sharpness={bg_lap:.0f}, brightness={bg_mean:.0f})."
        )

    if bg_std < 40 and bg_mean > 130:
        score += 35
        findings.append(
            f"<b>Highly uniform background</b> (std={bg_std:.1f}) — "
            f"AI generators synthesize flat background gradients."
        )
    else:
        findings.append(f"Natural background variation (std={bg_std:.1f}).")

    score = min(score, 100)

    return {
        "score": score,
        "max":   100,
        "raw":   score / 100,
        "explanation": "<br>".join(f"• {f}" for f in findings),
    }


# ═════════════════════════════════════════════════════
# ENGINE 7 — PORTRAIT STYLE ANALYSIS
# ═════════════════════════════════════════════════════

def engine_portrait_style(image: Image.Image) -> dict:
    """
    Detect AI portrait-style composition.
    """
    img  = np.array(image)
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY).astype(np.float64)
    hsv  = cv2.cvtColor(img, cv2.COLOR_RGB2HSV)

    h, w = gray.shape

    top_strip    = gray[:int(h*0.15), :]
    bottom_strip = gray[int(h*0.85):, :]
    left_strip   = gray[:, :int(w*0.12)]
    right_strip  = gray[:, int(w*0.88):]

    bg_regions = np.concatenate([
        top_strip.ravel(), bottom_strip.ravel(),
        left_strip.ravel(), right_strip.ravel()
    ])
    bg_mean  = float(np.mean(bg_regions))
    bg_std   = float(np.std(bg_regions))

    val_ch  = hsv[:,:,2].astype(np.float64)
    sat_ch  = hsv[:,:,1].astype(np.float64)
    white_mask = (val_ch > 210) & (sat_ch < 30)
    white_pct  = float(white_mask.mean() * 100)

    score = 0
    findings = []

    if white_pct > 15:
        score += 55
        findings.append(
            f"<b>Studio white backdrop coverage ({white_pct:.0f}% of image)</b> — "
            f"Typical of AI diffusion portrait framing."
        )
    elif white_pct > 5:
        score += 35
        findings.append(f"Significant white background area ({white_pct:.0f}%).")
    else:
        findings.append(f"No significant white background ({white_pct:.0f}%).")

    if bg_std < 40 and bg_mean > 130:
        score += 45
        findings.append(
            f"<b>Uniform studio background profile</b> (mean={bg_mean:.0f}, std={bg_std:.1f})."
        )
    elif bg_std < 60:
        score += 20
        findings.append(f"Smooth background profile (std={bg_std:.1f}).")

    score = min(score, 100)

    return {
        "score": score,
        "max":   100,
        "raw":   score / 100,
        "explanation": "<br>".join(f"• {f}" for f in findings),
    }


# ═════════════════════════════════════════════════════
# ENGINE 9 — FACE LANDMARK & FACIAL SYMMETRY FORENSICS
# ═════════════════════════════════════════════════════

_face_cascade = None

def _get_face_cascade():
    global _face_cascade
    if _face_cascade is None:
        try:
            cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'
            _face_cascade = cv2.CascadeClassifier(cascade_path)
        except Exception:
            _face_cascade = False
    return _face_cascade if _face_cascade is not False else None



def engine_face_symmetry(image: Image.Image) -> dict:
    """
    Detects face structure, facial symmetry, and micro-smoothness around facial region.
    AI synthetic faces often feature unnatural bilateral symmetry or hyper-smooth skin regions.
    """
    arr = np.array(image)
    gray = cv2.cvtColor(arr, cv2.COLOR_RGB2GRAY)
    
    cascade = _get_face_cascade()
    faces = cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(60, 60)) if cascade is not None else []

    
    score = 0
    findings = []

    if len(faces) == 0:
        findings.append("No distinct frontal face detected; evaluating central region micro-symmetry.")
        h, w = gray.shape
        cy, cx = h // 2, w // 2
        face_crop = gray[max(0, cy-100):min(h, cy+100), max(0, cx-100):min(w, cx+100)]
    else:
        x, y, w, h = faces[0]
        face_crop = gray[y:y+h, x:x+w]
        findings.append(f"<b>Frontal face localized ({w}x{h} px)</b>.")

    if face_crop.size > 0:
        fh, fw = face_crop.shape
        hw = fw // 2
        left_half = face_crop[:, :hw]
        right_half = cv2.flip(face_crop[:, fw-hw:], 1)
        
        min_h = min(left_half.shape[0], right_half.shape[0])
        min_w = min(left_half.shape[1], right_half.shape[1])
        
        diff = np.abs(left_half[:min_h, :min_w].astype(np.float64) - right_half[:min_h, :min_w].astype(np.float64))
        mean_brightness = np.mean(face_crop) + 1e-5
        rel_asymmetry = np.mean(diff) / mean_brightness
        
        # Face skin micro-texture blur variance
        lap_var = cv2.Laplacian(face_crop, cv2.CV_64F).var()
        
        if rel_asymmetry < 0.15:
            score += 50
            findings.append(f"<b>Unnatural facial symmetry (rel_diff={rel_asymmetry:.3f})</b> — AI portraits frequently synthesize perfectly symmetrical faces.")
        elif rel_asymmetry < 0.25:
            score += 30
            findings.append(f"Slightly elevated symmetry (rel_diff={rel_asymmetry:.3f}).")
        else:
            findings.append(f"Natural facial asymmetry (rel_diff={rel_asymmetry:.3f}).")

        if lap_var < 150:
            score += 45
            findings.append(f"<b>Facial region over-smoothing (sharpness={lap_var:.1f})</b> — Micro-texture loss in skin area.")
        elif lap_var < 350:
            score += 25
            findings.append(f"Moderate skin smoothness (sharpness={lap_var:.1f}).")
        else:
            findings.append(f"Natural skin micro-details present (sharpness={lap_var:.1f}).")

    score = min(score, 100)
    return {
        "score": score,
        "max": 100,
        "raw": score / 100.0,
        "explanation": "<br>".join(f"• {f}" for f in findings)
    }


# ═════════════════════════════════════════════════════
# ENGINE 10 — ERROR LEVEL ANALYSIS (ELA) & COMPRESSION
# ═════════════════════════════════════════════════════

def engine_ela_compression(image: Image.Image) -> dict:
    """
    Error Level Analysis (ELA).
    Re-compresses image at 90% JPEG quality and measures difference distribution.
    AI synthetic images have uniform error distribution, whereas authentic photos show variable error levels.
    """
    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=90)
    buffer.seek(0)
    recompressed = Image.open(buffer).convert("RGB")
    
    ela_img = ImageChops.difference(image.convert("RGB"), recompressed)
    extrema = ela_img.getextrema()
    max_diff = max([ex[1] for ex in extrema])
    if max_diff == 0:
        max_diff = 1
    
    scale = 255.0 / max_diff
    ela_scaled = ImageEnhance.Brightness(ela_img).enhance(scale)
    ela_arr = np.array(ela_scaled).astype(np.float64)
    
    ela_mean = float(np.mean(ela_arr))
    ela_std  = float(np.std(ela_arr))
    
    score = 0
    findings = []
    
    if ela_std < 12.0:
        score += 60
        findings.append(
            f"<b>Uniform compression error distribution (std={ela_std:.2f})</b> — "
            f"Synthetically generated images exhibit unnatural ELA consistency across regions."
        )
    elif ela_std < 18.0:
        score += 35
        findings.append(f"Low ELA variation (std={ela_std:.2f}) — typical of AI diffusion outputs.")
    else:
        findings.append(f"Natural ELA compression variation (std={ela_std:.2f}).")
        
    if ela_mean < 8.0:
        score += 35
        findings.append(f"Extremely low re-compression artifact residual (mean={ela_mean:.2f}).")
    elif ela_mean > 45.0:
        score += 20
        findings.append(f"High ELA energy residual (mean={ela_mean:.2f}).")
        
    score = min(score, 100)
    return {
        "score": score,
        "max": 100,
        "raw": score / 100.0,
        "explanation": "<br>".join(f"• {f}" for f in findings)
    }


def engine_watermark_detection(image: Image.Image) -> dict:
    """Detect likely text/logo watermarks in the image margins."""
    frame = np.asarray(image.convert("RGB"))
    height, width = frame.shape[:2]
    border_x = max(int(width * 0.14), 64)
    border_y = max(int(height * 0.14), 48)
    regions = [
        frame[:border_y, :border_x],
        frame[:border_y, -border_x:],
        frame[-border_y:, :border_x],
        frame[-border_y:, -border_x:],
    ]

    text_like_regions = 0
    for region in regions:
        gray = cv2.cvtColor(region, cv2.COLOR_RGB2GRAY)
        edges = cv2.Canny(gray, 100, 200)
        contours, _ = cv2.findContours(edges, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
        
        char_boxes = []
        region_area = region.shape[0] * region.shape[1]
        for contour in contours:
            x, y, w, h = cv2.boundingRect(contour)
            area = w * h
            aspect = w / (h + 1e-5)
            if 6 <= w <= region.shape[1] * 0.4 and 8 <= h <= region.shape[0] * 0.35 and 40 <= area <= region_area * 0.1:
                if 0.2 <= aspect <= 3.0:
                    char_boxes.append((x, y, w, h))
                    
        if len(char_boxes) >= 5:
            ys = [b[1] for b in char_boxes]
            hs = [b[3] for b in char_boxes]
            y_std = float(np.std(ys))
            h_cv = float(np.std(hs) / (np.mean(hs) + 1e-5))
            if y_std < region.shape[0] * 0.12 and h_cv < 0.45:
                text_like_regions += 1

    detected = text_like_regions >= 1
    return {
        "score": 100 if detected else 0,
        "max": 100,
        "raw": 1.0 if detected else 0.0,
        "active": True,
        "detected": detected,
        "explanation": "Watermark or logo-like text detected in the image margin." if detected else "No watermark pattern detected.",
    }


# ═════════════════════════════════════════════════════
# ENGINE 11 — FINE-TUNED VIT CLASSIFIER ENGINE
# ═════════════════════════════════════════════════════

@st.cache_resource(show_spinner=False)
def _get_fine_tuned_vit_resources(model_dir: str, mtime: float = 0.0):
    processor = ViTImageProcessor.from_pretrained(model_dir)
    model = ViTForImageClassification.from_pretrained(model_dir)
    model.eval()
    return processor, model

def engine_fine_tuned_vit(image: Image.Image) -> dict:
    """
    Evaluates image against fine-tuned ViT checkpoint if available in ./fine_tuned_vit.
    """
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    model_dir = os.path.join(project_root, "fine_tuned_vit")
    st_path = os.path.join(model_dir, "model.safetensors")
    bin_path = os.path.join(model_dir, "pytorch_model.bin")
    if not os.path.exists(st_path) and not os.path.exists(bin_path):
        return {
            "score": 0, "max": 100, "raw": 0.0, "active": False,
            "explanation": "Local fine-tuned ViT checkpoint not trained yet. Run train.py to activate.",
        }
        
    try:
        mtime = os.path.getmtime(st_path) if os.path.exists(st_path) else os.path.getmtime(bin_path)
        processor, model = _get_fine_tuned_vit_resources(model_dir, mtime)

        inputs = processor(images=image.convert("RGB"), return_tensors="pt")
        with torch.no_grad():
            outputs = model(**inputs)
            probs = torch.nn.functional.softmax(outputs.logits, dim=-1)[0]
            
        ai_prob = float(probs[0].item()) # 0: artificial, 1: real
        score_100 = round(ai_prob * 100, 1)
        
        return {
            "score": score_100,
            "max": 100,
            "raw": ai_prob,
            "active": True,
            "explanation": f"<b>Fine-Tuned ViT Model Output:</b> {score_100}% AI confidence."
        }
    except Exception as exc:
        return {
            "score": 0, "max": 100, "raw": 0.0, "active": False,
            "explanation": f"Failed to load fine-tuned model: {exc}",
        }


# ═════════════════════════════════════════════════════
# ENGINE 13 — AI INPAINTING & LOCAL MANIPULATION ENGINE
# ═════════════════════════════════════════════════════

def engine_ai_manipulation_and_inpainting(image: Image.Image) -> dict:
    """
    Scans for localized AI generative inpainting, object removal, and retouching
    on otherwise authentic camera photographs using robust wavelet residual disparity.
    """
    try:
        import pywt
        from scipy.ndimage import laplace
        import scipy.stats as stats
        
        rgb = np.asarray(image.convert("RGB")).astype(np.float32) / 255.0
        h, w, _ = rgb.shape
        r, g, b = rgb[..., 0], rgb[..., 1], rgb[..., 2]
        gray = 0.299 * r + 0.587 * g + 0.114 * b

        grid_r, grid_c = 6, 6
        th, tw = max(4, h // grid_r), max(4, w // grid_c)
        
        tile_noise = []
        tile_ratio = []
        
        for r_idx in range(grid_r):
            for c_idx in range(grid_c):
                t = gray[r_idx*th:(r_idx+1)*th, c_idx*tw:(c_idx+1)*tw]
                coeffs = pywt.dwt2(t, 'db4')
                _, (_, _, hh) = coeffs
                sigma = float(np.median(np.abs(hh)) / 0.6745)
                l_var = float(laplace(t).var())
                
                tile_noise.append(sigma)
                tile_ratio.append(sigma / (np.sqrt(l_var) + 1e-4))
                
        n_arr = np.array(tile_noise, dtype=np.float32)
        r_arr = np.array(tile_ratio, dtype=np.float32)
        
        n_med = float(np.median(n_arr))
        n_iqr = float(stats.iqr(n_arr)) + 1e-5
        n_z = np.abs(n_arr - n_med) / n_iqr
        
        r_med = float(np.median(r_arr))
        r_iqr = float(stats.iqr(r_arr)) + 1e-5
        r_z = np.abs(r_arr - r_med) / r_iqr
        
        anomalies = int(np.sum((n_z > 3.5) & (r_z > 3.0)))
        max_nz = float(np.max(n_z))
        max_rz = float(np.max(r_z))
        
        is_edited = bool(anomalies >= 1 and max_nz >= 4.0 and max_rz >= 3.2)
        if is_edited:
            score = float(np.clip(max_nz * 12.0, 65.0, 100.0))
        else:
            score = float(np.clip(min(max_rz, 2.5) * 6.0, 0.0, 20.0))

        findings = []
        if is_edited:
            findings.append(f"Detected localized AI inpainting / object removal ({anomalies} anomaly patch(es), noise disparity z={max_nz:.2f}).")
        else:
            findings.append("Uniform sensor noise distribution across all image tiles.")

        return {
            "score": round(score, 1),
            "max": 100,
            "raw": score / 100.0,
            "is_edited": is_edited,
            "anomalies": anomalies,
            "explanation": "<br>".join(f"• {f}" for f in findings)
        }
    except Exception as exc:
        return {
            "score": 0, "max": 100, "raw": 0.0, "is_edited": False, "anomalies": 0,
            "explanation": f"Inpainting scan skipped: {exc}"
        }
    except Exception as exc:
        return {
            "score": 0, "max": 100, "raw": 0.0, "is_edited": False, "anomalies": 0,
            "explanation": f"Inpainting scan skipped: {exc}"
        }


# ═════════════════════════════════════════════════════
# MAIN ANALYSIS
# ═════════════════════════════════════════════════════

def full_image_analysis(image: Image.Image) -> dict:
    """
    Run 13 forensic, neural, provenance, and signal processing engines and produce a final weighted verdict
    calibrated for modern AI diffusion models and localized AI edits.
    """
    working_image = image.copy()
    working_image.thumbnail((1024, 1024), Image.Resampling.LANCZOS)
    
    neural   = engine_neural_ensemble(working_image)
    clip     = engine_clip_semantic(working_image)
    texture  = engine_texture_smoothness(working_image)
    color    = engine_color_forensics(working_image)
    freq     = engine_frequency(working_image)
    edge     = engine_edge_sharpness(working_image)
    portrait = engine_portrait_style(working_image)
    face     = engine_face_symmetry(working_image)
    ela      = engine_ela_compression(working_image)
    watermark = engine_watermark_detection(working_image)
    ft_vit   = engine_fine_tuned_vit(working_image)
    provenance = engine_ai_provenance(working_image)
    manipulation = engine_ai_manipulation_and_inpainting(working_image)

    engines_dict = {
        "neural_ensemble": {
            "name": "Neural Network Ensemble",
            "icon": "🧠",
            **neural,
        },
        "clip_semantic": {
            "name": "CLIP Semantic Analysis",
            "icon": "🔬",
            **clip,
        },
        "texture_smoothness": {
            "name": "Texture Smoothness Analysis",
            "icon": "🎨",
            **texture,
        },
        "color_forensics": {
            "name": "Color & Saturation Forensics",
            "icon": "🌈",
            **color,
        },
        "frequency": {
            "name": "Frequency Domain (FFT)",
            "icon": "📊",
            **freq,
        },
        "edge_sharpness": {
            "name": "Background & Edge Analysis",
            "icon": "🔍",
            **edge,
        },
        "portrait_style": {
            "name": "Portrait Style Analysis",
            "icon": "🪞",
            **portrait,
        },
        "face_symmetry": {
            "name": "Face Symmetry & Micro-Texture",
            "icon": "👤",
            **face,
        },
        "ela_compression": {
            "name": "Error Level Analysis (ELA)",
            "icon": "🖼️",
            **ela,
        },
        "fine_tuned_vit": {
            "name": "Fine-Tuned ViT Classifier",
            "icon": "⚡",
            **ft_vit,
        },
        "watermark_detection": {
            "name": "Watermark Detection",
            "icon": "🏷️",
            **watermark,
        },
        "ai_provenance": {
            "name": "AI & Generator Provenance Engine",
            "icon": "🧬",
            **provenance,
        },
        "ai_manipulation": {
            "name": "AI Inpainting & Retouch Forensics",
            "icon": "🪄",
            **manipulation,
        },
    }

    total_engine_count = len(engines_dict)
    weighted_engine_scores = []
    for engine_key, engine in engines_dict.items():
        if engine["max"] <= 0:
            continue
        ai_percentage = engine["score"] / engine["max"] * 100
        weight = 15.0 if engine_key == "fine_tuned_vit" and engine.get("active") else 1.0
        if engine_key == "ai_provenance":
            weight = 1.5
        if engine_key == "ai_manipulation":
            weight = 1.2
        weighted_engine_scores.append((ai_percentage, weight))

    engine_ai_percentages = [score for score, _weight in weighted_engine_scores]
    high_risk_engine_count = sum(percent > 60 for percent in engine_ai_percentages)
    human_engine_count = total_engine_count - high_risk_engine_count

    total_weight = sum(weight for _score, weight in weighted_engine_scores)
    ai_conf = sum(score * weight for score, weight in weighted_engine_scores) / (total_weight * 100)
    human_conf = 1.0 - ai_conf

    # Real but Edited by AI decision logic
    is_edited_flag = bool(manipulation.get("is_edited", False))

    if ai_conf >= 0.58:
        verdict       = "AI-GENERATED"
        verdict_label = "🚨 AI-GENERATED"
    elif is_edited_flag and ai_conf <= 0.55:
        verdict       = "AI-EDITED"
        verdict_label = "🪄 LIKELY REAL BUT EDITED BY AI"
    elif human_conf >= 0.50:
        verdict       = "AUTHENTIC"
        verdict_label = "✅ AUTHENTIC"
    else:
        verdict       = "UNCERTAIN"
        verdict_label = "⚠️ UNCERTAIN"

    return {
        "verdict":          verdict,
        "verdict_label":    verdict_label,
        "confidence_score": round(ai_conf * 100, 1),
        "human_score":      round(human_conf * 100, 1),
        "is_ai_edited":     is_edited_flag or verdict == "AI-EDITED",
        "ai_edited_score":  round(float(manipulation.get("score", 0)), 1),
        "total_engine_count": total_engine_count,
        "high_risk_engine_count": high_risk_engine_count,
        "human_engine_count":     human_engine_count,
        "engines":          engines_dict,
        "ai_probability": round(ai_conf, 4),
        "real_probability": round(human_conf, 4),
        "confidence": round(abs(ai_conf - human_conf), 4),
        "nearest_generator": provenance.get("generator", "Unknown AI"),
        "similarity": round(provenance.get("raw", 0.5), 4),
        "detected_artifacts": [
            e.get("name", key) for key, e in engines_dict.items()
            if e.get("score", 0) >= 60
        ],
        "feature_scores": {key: round(float(e.get("score", 0)), 2) for key, e in engines_dict.items()},
        "reason": provenance.get("explanation", "Multi-engine forensic consensus."),
        "top_matches": [],
    }


def full_profile_analysis(
    image=None,
    username="",
    bio="",
    followers=0,
    posts=0,
    following=0,
    account_age_days=0,
    image_source=None,
):
    """Analyze an image and expose the legacy profile-analysis response shape.

    The Streamlit profile view and older callers use profile-oriented key names,
    while the primary detector returns an engine-oriented result.  Keep both
    APIs working by adapting the detector output instead of duplicating the
    image analysis.
    """
    # Older profile UI code uses ``image_source``.  Accept it as an alias so
    # both profile app variants can call this shared detector.
    if image is None:
        image = image_source
    if image is None:
        raise ValueError("An image is required for profile analysis.")

    analysis = full_image_analysis(image)
    score = analysis["confidence_score"]
    engines = analysis["engines"]

    metadata_score = 0
    red_flags = []
    if followers < 10 and following > 100:
        metadata_score += 30
        red_flags.append("Low followers with high following")
    if posts == 0:
        metadata_score += 25
        red_flags.append("No posts")
    if account_age_days and account_age_days < 30:
        metadata_score += 20
        red_flags.append("Recently created account")
    if len(username) > 12 and any(char.isdigit() for char in username):
        metadata_score += 15
        red_flags.append("Suspicious username pattern")
    if not bio.strip():
        metadata_score += 10
        red_flags.append("Empty profile bio")
    metadata_score = min(metadata_score, 100)

    return {
        "overall_suspicion_score": score,
        # Use the ASCII identifier here so legacy console callers also work
        # on Windows terminals that default to a non-UTF-8 code page.
        "overall_verdict": analysis["verdict"],
        "image_analysis": {
            "ai_probability": score / 100,
            "is_ai_generated": analysis["verdict"] == "AI-GENERATED",
            "confidence_level": "high" if score >= 65 else "medium" if score >= 40 else "low",
            "individual_results": engines,
        },
        "metadata_analysis": {
            "metadata_suspicion_score": metadata_score,
            "red_flags": red_flags,
        },
        "clip_score": engines["clip_semantic"]["score"],
        "artifact_score": engines["texture_smoothness"]["score"],
        "symmetry_score": engines["face_symmetry"]["score"],
        "frequency_score": engines["frequency"]["score"],
        "watermark_score": engines["watermark_detection"]["score"],
    }
